### ISSUE TITLE
Question about the Hierarchical Task Annotation

### ISSUE THREAD

**Issue by 594zyc** [SamsonYuBaiJian/actionet#1]
Hi,

Thanks for open-sourcing the dataset! After going through it, I have two questions regarding the hierarchical task annotation: 
(1) Is the task description divided into several sub-goals (as shown in Figure 2 in the paper), or just plain text as in the repository? 
(2) Do you annotate the alignment of phrases in task descriptions to the video frames as shown in Figure 1 in the paper? 

Thanks!
Yichi

**Comment by SamsonYuBaiJian** [comment]
Hi @594zyc , thank you for checking out this work.

Regarding your two questions:
(1) Is the task description divided into several sub-goals (as shown in Figure 2 in the paper), or just plain text as in the repository?

**We have a script that can group the atomic level actions into its sub-goals, however due to the IP rights of this work, we cannot release the script, but you can write your own script to group them into sub-goals.**

(2) Do you annotate the alignment of phrases in task descriptions to the video frames as shown in Figure 1 in the paper?

**We have that too but due to IP of the research grant, we cannot release that. But each atomic action should be aligned to the corresponding frames.**

**Comment by 594zyc** [comment]
Hi @SamsonYuBaiJian,

Get it. Thank you very much for the quick response!
